# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BusNotification' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Firebase/Core', '~> 4.13.0'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'GoogleSignIn'
pod 'Fabric', '~> 1.7.7'
pod 'Crashlytics', '~> 3.10.2'
pod 'Firebase/AdMob'

end
